# Generated by Django 3.2.8 on 2021-10-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0002_auto_20211026_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_sap_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoqueproduto', to='produto.cadastroprodutos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
