# Generated by Django 3.2.8 on 2021-12-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '__first__'),
        ('produto', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('quantidade_entregue', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_sap_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoqueproduto', to='produto.cadastroprodutos')),
                ('nome_produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoquenome', to='produto.cadastroprodutos')),
                ('valor_unitario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valorinsumo', to='insumo.cadastroinsumo')),
            ],
            options={
                'verbose_name': 'Estoque Almoxarifado',
                'verbose_name_plural': 'Estoques Insumos',
            },
        ),
    ]
