# Generated by Django 3.2.8 on 2021-10-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_auto_20211026_1143'),
        ('produto', '0002_auto_20211026_1143'),
        ('almox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquealmoxarifado',
            options={'verbose_name': 'Estoque Almoxarifado', 'verbose_name_plural': 'Estoques Insumos'},
        ),
        migrations.AddField(
            model_name='estoquealmoxarifado',
            name='nome_produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoquenome', to='produto.cadastroprodutos'),
        ),
        migrations.AddField(
            model_name='estoquealmoxarifado',
            name='quantidade_entregue',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='estoquealmoxarifado',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='estoquealmoxarifado',
            name='valor_unitario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valorinsumo', to='insumo.cadastroinsumo'),
        ),
    ]
