# Generated by Django 3.2.8 on 2021-12-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModoManufatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('modo_manufatura', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Modo de Manufatura',
                'verbose_name_plural': 'Modos Manufatura',
            },
        ),
        migrations.CreateModel(
            name='TipoManufatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_manufatura', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Manufatura',
                'verbose_name_plural': 'Tipos de Manufatura',
            },
        ),
        migrations.CreateModel(
            name='ExecucaoManufatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('numero_serie', models.IntegerField(unique=True)),
                ('quantidade_produto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inicio_manufatura', models.DateTimeField(auto_now_add=True)),
                ('fim_manufatura', models.DateTimeField(auto_now_add=True)),
                ('executante_inicio', models.CharField(max_length=100)),
                ('executante_final', models.CharField(max_length=99)),
                ('manufatura_finalizada', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_sap_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucaocodigoproduto', to='produto.cadastroprodutos')),
                ('modo_manufatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucaomanufaturamodo', to='manufatura.modomanufatura')),
                ('nome_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucaonomeproduto', to='produto.cadastroprodutos')),
                ('tipo_manufatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucaotipomanufatura', to='manufatura.tipomanufatura')),
            ],
            options={
                'verbose_name': 'Execução Manufatura',
                'verbose_name_plural': 'Execuções Manufatura',
            },
        ),
    ]
