# Generated by Django 3.2.8 on 2021-10-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20211026_1143'),
        ('manufatura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModoManufatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('modo_manufatura', models.CharField(max_length=100)),
                ('tipo_manufatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modotipomanufatura', to='manufatura.tipomanufatura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecucaoManufatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('numero_serie', models.IntegerField(unique=True)),
                ('quantidade_produto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inicio_manufatura', models.DateTimeField(auto_now_add=True)),
                ('fim_manufatura', models.DateTimeField(auto_now_add=True)),
                ('executante_inicio', models.CharField(max_length=100)),
                ('executante_final', models.CharField(max_length=100)),
                ('codigo_sap_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucaocodigoproduto', to='produto.cadastroprodutos')),
                ('modo_manufatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucaomanufaturamodo', to='manufatura.modomanufatura')),
                ('nome_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucaonomeproduto', to='produto.cadastroprodutos')),
                ('tipo_manufatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucaotipomanufatura', to='manufatura.tipomanufatura')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
