# Generated by Django 3.2.8 on 2021-10-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufatura', '0002_execucaomanufatura_modomanufatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execucaomanufatura',
            options={'verbose_name': 'Execução Manufatura', 'verbose_name_plural': 'Execuções Manufatura'},
        ),
        migrations.AlterModelOptions(
            name='modomanufatura',
            options={'verbose_name': 'Modo Manufatura', 'verbose_name_plural': 'Modos Manufatura'},
        ),
        migrations.AlterModelOptions(
            name='tipomanufatura',
            options={'verbose_name': 'Tipo Manufatura', 'verbose_name_plural': 'Tipos de Manufatura'},
        ),
    ]
