# Generated by Django 3.2.8 on 2021-12-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufatura', '0004_execucaomanufatura_manufatura_finalizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modomanufatura',
            name='tipo_manufatura',
        ),
    ]
