# Generated by Django 3.2.8 on 2021-12-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufatura', '0005_remove_modomanufatura_tipo_manufatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modomanufatura',
            name='modo_manufatura',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipomanufatura',
            name='tipo_manufatura',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
