# Generated by Django 3.2.8 on 2021-12-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufatura', '0006_auto_20211216_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modomanufatura',
            options={'verbose_name': 'Modo de Manufatura', 'verbose_name_plural': 'Modos Manufatura'},
        ),
    ]
