# Generated by Django 3.2.8 on 2021-10-25 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufatura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_sap', models.IntegerField(unique=True)),
                ('nome_produto', models.CharField(max_length=150)),
                ('descricao_produto', models.TextField(max_length=300)),
                ('utilizacao', models.CharField(max_length=100)),
                ('projeto', models.FileField(upload_to='projeto/')),
                ('foto', models.ImageField(upload_to='foto/')),
                ('tipo_manufatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufatura.tipomanufatura')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
