# Generated by Django 3.2.8 on 2021-12-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroprodutos',
            name='nome_produto',
            field=models.CharField(max_length=150),
        ),
    ]
