# Generated by Django 3.2.8 on 2021-12-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20211026_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroprodutos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
        migrations.AlterField(
            model_name='cadastroprodutos',
            name='projeto',
            field=models.FileField(blank=True, null=True, upload_to='projeto/'),
        ),
    ]
