# Generated by Django 3.2.8 on 2021-12-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20211207_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroprodutos',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='cadastroprodutos',
            name='projeto',
        ),
    ]
