# Generated by Django 3.2.8 on 2021-12-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20211207_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastroprodutos',
            options={'verbose_name': 'Cadastro de Produto', 'verbose_name_plural': 'Cadastro de Produtos'},
        ),
    ]
