# Generated by Django 3.2.8 on 2021-10-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_sap', models.IntegerField(unique=True)),
                ('descricao_insumo', models.CharField(max_length=100)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Cadastro Insumo',
                'verbose_name_plural': 'Cadastro Insumos',
            },
        ),
        migrations.CreateModel(
            name='UnidadeEngenharia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'verbose_name': 'Unidade Engenharia',
                'verbose_name_plural': 'Unidades Engenharia',
            },
        ),
        migrations.CreateModel(
            name='EstoqueInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('codigo_sap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumosap', to='insumo.cadastroinsumo')),
                ('descricao_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumodescricao', to='insumo.cadastroinsumo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumounidade', to='insumo.unidadeengenharia')),
            ],
            options={
                'verbose_name': 'Estoque Insumo',
                'verbose_name_plural': 'Estoque Insumos',
            },
        ),
    ]
