# Generated by Django 3.2.8 on 2021-12-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumo', to='insumo.cadastroinsumo'),
        ),
    ]
