# Generated by Django 3.2.8 on 2021-10-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastroinsumo',
            old_name='codigo_sap',
            new_name='codigo_sap_insumo',
        ),
        migrations.RenameField(
            model_name='estoqueinsumo',
            old_name='codigo_sap',
            new_name='codigo_sap_insumo',
        ),
    ]
