# Generated by Django 3.2.8 on 2021-10-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_auto_20211026_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroinsumo',
            name='codigo_sap_insumo',
            field=models.IntegerField(default='', unique=True),
        ),
    ]
