# Generated by Django 3.2.8 on 2021-12-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_alter_estoqueinsumo_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.cadastroinsumo'),
        ),
    ]
