# Generated by Django 3.2.8 on 2021-10-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0003_alter_cadastroinsumo_codigo_sap_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroinsumo',
            name='codigo_sap_insumo',
            field=models.IntegerField(unique=True),
        ),
    ]
