# Generated by Django 3.2.8 on 2021-12-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0003_alter_estoqueinsumo_insumo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoqueinsumo',
            old_name='insumo',
            new_name='descricao_insumo',
        ),
    ]
