# Generated by Django 3.2.8 on 2021-12-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0005_remove_cadastroinsumo_valor_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueinsumo',
            name='codigo_sap_insumo',
        ),
    ]
