# Generated by Django 3.2.8 on 2021-12-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0006_remove_estoqueinsumo_codigo_sap_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueinsumo',
            name='descricao_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.cadastroinsumo'),
        ),
    ]
