# Generated by Django 3.2.8 on 2021-12-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0007_alter_estoqueinsumo_descricao_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueinsumo',
            name='descricao_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descricaoinsumo', to='insumo.cadastroinsumo'),
        ),
    ]
