# Generated by Django 3.2.8 on 2021-12-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0008_alter_estoqueinsumo_descricao_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueInsumoTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cadastroInsumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.cadastroinsumo')),
            ],
            options={
                'verbose_name': 'Estoque Insumo Teste',
                'verbose_name_plural': 'Estoque InsumosTeste',
            },
        ),
    ]
