# Generated by Django 3.2.8 on 2021-12-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0009_estoqueinsumoteste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstoqueInsumoTeste',
        ),
    ]
